version: "3"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "db"

  wp:
    depends_on:
      - db
    build: ./
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $DB_NAME
      XDEBUG_CONFIG: client_host=host.docker.internal
      WORDPRESS_DEBUG: true
    volumes:
      - ./wordpress:/var/www/html
      - ./themes/new-theme:/var/www/html/wp-content/themes/new-theme
      - ./uploads:/var/www/html/wp-content/uploads

  webserver:
    depends_on:
      - wp
    image: nginx:1.15.12-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./themes/new-theme:/var/www/html/wp-content/themes/new-theme
      - ./uploads:/var/www/html/wp-content/uploads

volumes:
  dbdata:
